# Generated by Django 4.1.4 on 2022-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photos', models.ImageField(upload_to='product_photos/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.listing')),
            ],
        ),
    ]
