# Generated by Django 4.1.4 on 2022-12-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_thread_message_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
