# Generated by Django 4.1.4 on 2022-12-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
