# Generated by Django 4.1.4 on 2022-12-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_productimage_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.listing'),
        ),
    ]
