# Generated by Django 4.1.4 on 2022-12-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id']},
        ),
    ]
